// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjwbMeTJ1PMtBCW-UPuGeqQk4-pkskFnw',
    appId: '1:467864136399:web:8d1d91c4052076a718e5ba',
    messagingSenderId: '467864136399',
    projectId: 'firstapp-8fba4',
    authDomain: 'firstapp-8fba4.firebaseapp.com',
    databaseURL: 'https://firstapp-8fba4-default-rtdb.firebaseio.com',
    storageBucket: 'firstapp-8fba4.firebasestorage.app',
    measurementId: 'G-P67N6ZFYND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjtsRihMQAmY0ePxeAISRWd_O51Y20jp4',
    appId: '1:467864136399:android:5614a20b1ad8d9f218e5ba',
    messagingSenderId: '467864136399',
    projectId: 'firstapp-8fba4',
    databaseURL: 'https://firstapp-8fba4-default-rtdb.firebaseio.com',
    storageBucket: 'firstapp-8fba4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSZuvd6YKFqoqdjeGUzyBO11DuiOBSE2I',
    appId: '1:467864136399:ios:b17eed8db8be149618e5ba',
    messagingSenderId: '467864136399',
    projectId: 'firstapp-8fba4',
    databaseURL: 'https://firstapp-8fba4-default-rtdb.firebaseio.com',
    storageBucket: 'firstapp-8fba4.firebasestorage.app',
    iosBundleId: 'com.example.personalitytest',
  );
}
